name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          corepack: true

      - name: Install dependencies
        run: yarn install

      - name: Run formatter
        run: yarn format

      - name: Build project
        run: yarn build
