name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Run formatter
        run: yarn format

      - name: Build project
        run: yarn build

      - name: Commit and push dist changes
        if: github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/
          if ! git diff --staged --quiet; then
            git commit -m "Auto-build: Update dist folder [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
