name: Release

on:
  release:
    types: [created]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          corepack: true

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stoneham-override-calculator-dist
          path: dist/
          retention-days: 90