name: Release

on:
  release:
    types: [created]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Create release archive
        run: |
          cd dist
          zip -r ../stoneham-override-calculator-${{ github.event.release.tag_name }}.zip .
          cd ..

      - name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Upload the zip archive
          gh release upload ${{ github.event.release.tag_name }} stoneham-override-calculator-${{ github.event.release.tag_name }}.zip

          # Upload individual files as well
          gh release upload ${{ github.event.release.tag_name }} dist/stoneham-override-calculator.js
          gh release upload ${{ github.event.release.tag_name }} dist/stoneham-override-calculator.js.map
          gh release upload ${{ github.event.release.tag_name }} dist/index.html
          gh release upload ${{ github.event.release.tag_name }} dist/style.css
